package entity

// Code generated by go generate; DO NOT EDIT.
const (
	TYPE_LEAGUE = "League"
)

type League struct {
	Title    string `db:"title" json:"title"`
	Short    string `db:"short" json:"short"`
	Games    int    `db:"games" json:"games"`
	Id       int    `db:"id" json:"id"`
	SportId  int    `db:"sport_id" json:"sportId"`
	IsActive bool   `db:"is_active" json:"isActive"`
}

func (e *League) CheckIsActive() bool {
	return e.IsActive == true
}
