package entity

// Code generated by go generate; DO NOT EDIT.
const (
	TYPE_PLAYER = "Player"
)

type Player struct {
	Id        int    `db:"id" json:"id"`
	SportId   int    `db:"sport_id" json:"sportId"`
	LeagueId  int    `db:"league_id" json:"leagueId"`
	TeamId    int    `db:"team_id" json:"teamId"`
	Name      string `db:"name" json:"name"`
	BirthDate string `db:"birth_date" json:"birthDate"`
	IsActive  bool   `db:"is_active" json:"isActive"`
}

func (e *Player) CheckIsActive() bool {
	return e.IsActive == true
}
