package entity

// Code generated by go generate; DO NOT EDIT.
const (
	TYPE_SPORT = "Sport"
)

type Sport struct {
	Short    string `db:"short" json:"short"`
	IsActive bool   `db:"is_active" json:"isActive"`
	Id       int    `db:"id" json:"id"`
	Title    string `db:"title" json:"title"`
}

func (e *Sport) CheckIsActive() bool {
	return e.IsActive == true
}
