package entity

// Code generated by go generate; DO NOT EDIT.
const (
	TYPE_TEAM = "Team"
)

type Team struct {
	LeagueId int    `db:"league_id" json:"leagueId"`
	Title    string `db:"title" json:"title"`
	IsActive bool   `db:"is_active" json:"isActive"`
	Id       int    `db:"id" json:"id"`
	SportId  int    `db:"sport_id" json:"sportId"`
}

func (e *Team) CheckIsActive() bool {
	return e.IsActive == true
}
